---

- name: Configure NTP Server(s)
  ansible.builtin.ini_file:
    path: /etc/systemd/timesyncd.conf
    section: Time
    option: NTP
    value: "{{ timesyncd_servers }}"
    backup: yes
    no_extra_spaces: yes
  notify: restart systemd-timesyncd

- name: Uncomment Other Parameters
  ansible.builtin.replace:
    path: /etc/systemd/timesyncd.conf
    regexp: '^#{{ item }}(=.*)$'
    replace: '{{ item }}\1'
  loop: 
    - "{{ timesyncd_params }}"
  notify: restart systemd-timesyncd

- name: Check NTP Config
  command: |
    /usr/bin/timedatectl show --property=NTP --value
  register: ntp_config
  changed_when: ntp_config.rc != 0

- name: Enable NTP Sync
  command: |
    /usr/bin/timedatectl set-ntp true
  when: ntp_config.stdout_lines[-1] != "yes"
  notify: restart systemd-timesyncd

- name: Configure TimeZone
  timezone:
    name: "{{ timezone }}"
  notify: restart systemd-timesyncd
  when: ansible_service_mgr == "systemd"


...
